language: node_js
node_js: stable
dist: trusty
sudo: required
env:
  global:
  - secure: gZ5vpMlc9fuKSZeMmT6xf4+FIVWxET6f6Lkp6l5Qo9vL2X/KC/bMJF1v2w5xXFLFTdm/hPUDkeQRDUBBJhGcsXhJeWIvAXdPkObV9ZPRwpDnnN1qU5lOqVIy6gFjDm2Wm6UNXcRnyP1TrGpMwbG13EUtD0rF8LZqBm3B833sKS4=
  - secure: DObDewETPYiIsASeC3UETPbQ6YBniRZdNV2eTM1xULvuFNDxXJD09KKyWOiMduublEIJRXLjBIXmD8cbVsgrbRUYA4bxcXffDeuc6q6HaQGU9HvIbLz6o3/oxi4fX2G9GwrZtijW2p2Rgw2l9koR3ovjcM97CSTWFUMh5rtXag8=
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
deploy:
  provider: npm
  email: misha@ginkgobioworks.com
  api_key:
    secure: GNgiDsmZWecbQCzEPCJvo1nyrF7dlu2lCfNjFE3eEh83PUyMhi3Oqk6YvzmusQsJJ50dYAdl9HJN05Jpyu3TW2DcZE+CLjuTmmHZI33aLXKftETgrIkM5bJddy2Bj+uZ4kFlo+fQL7BtwvcEJyFhYA1oEDJZmMLze5JVelhFJgbviahedpTyJFb39qT39hXBc29BXCFqXARtHEY/skUhDfVUzV7WnoaqqtawsvtwJHWgHTLzoFYPG+b2EVE8qaJeL3xPH+weAhOKDve6nDoQlMS+jRSV4fgNS/4DRUyzSouu18vm7GcGlo4OMRWW9n5eZerw3Kdhv9NgQFYMKFtBRJlACOjPY8Fe1nkqGQLLuUAzmhfsg+PF8Is8GOi+qMMM6D0fART/A49e7rhiuIxIkQ87ZFTDXf6Sp3eWFpPpKSHsZlO/B06HdDv4Yn9VX9/ELoTA6VA0oLzxP1RY6YjVSPk4upoyBEna4vBgZ0abPAFvjlDcV4iPkFV79lHQmdh1J48gnuINRA6Fezv2wTUj42rm0tnK4p8bKnp7A0ZlqxeZMdrvcLhbeWi9LZ1ylewDcXgTH1Xb8GbeXDFx1d1P0LIkXnC5/Wq2+KCBb4gizsfh1+p8kTWRkDmw4B4hjBWeB/7qmdsegwLq6PQi3456rdxkfsC5Q/PzyxbH1qGlGz8=
  on:
    tags: true
    repo: ginkgobioworks/plotly-plot
  after_deploy:
  # Deploy the documentation on GitHub Pages
  - ./deploy/gp-build ginkgobioworks plotly-plot "Ginkgo Developer" devs@ginkgobioworks.com
